export let spriteList = [
  [10, null],
  [155, {
    "spirit": "Genis",
    "type": "Lesser Fae",
    "court": "Neutral",
    "conjureMsg": "§lGenis§r answers the call, hoping that it can provide assistance.",
    "likedOffering": "minecraft:apple",
    "dislikedOffering": "minecraft:carrot",
    "HoP": [5000, 7000],
    "spells": ["Magic Missile", "Magic Shield"],
    "trust": 20,
    "likedCandle": "wax"
  }],
  [15, {
    "spirit": "Chlorophae",
    "type": "Lesser Fae",
    "court": "Solar",
    "conjureMsg": "A §aChlorophae§r peeks at you from the Wilds with curiosity. Its favor goes with you.",
    "likedOffering": "minecraft:bone_meal",
    "dislikedOffering": "bw:fire_charge",
    "HoP": [5000, 7000],
    "spells": ["Green Thumb", "Conceal", "Absorb"],
    "trust": 15,
    "likedCandle": "lime"
  }],
  [15, {
    "spirit": "Vodyan",
    "type": "Lesser Fae",
    "court": "Solar",
    "conjureMsg": "A §3Vodyan§r looks up at you from beyond The Deep. It finds you interesting so it grants you its favor.",
    "likedOffering": "minecraft:seagrass",
    "dislikedOffering": "minecraft:blaze_powder",
    "HoP": [2000, 4000],
    "spells": ["Conceal", "Splash", "Mist", "Vodyan Blessing"],
    "trust": 10,
    "likedCandle": "cyan"
  }],
  [15, {
    "spirit": "Wildfyre",
    "type": "Lesser Fae",
    "court": "Solar",
    "conjureMsg": "You feel an intense burning stare into you. You have gotten the attention of a §cWildfyre§r.",
    "likedOffering": "minecraft:gunpowder",
    "dislikedOffering": "minecraft:snowball",
    "HoP": [5000, 7000],
    "spells": ["Blaze", "Conceal", "Fire Skin", "Fireball", "Heat"],
    "trust": 5,
    "likedCandle": "orange"
  }],
  [15, {
    "spirit": "Iceling",
    "type": "Lesser Fae",
    "court": "Lunar",
    "conjureMsg": "Frigid winds wrap around you, and an §bIceling§r giggles into your ear. It has answered your Call.",
    "likedOffering": "minecraft:snowball",
    "dislikedOffering": "minecraft:fire_charge",
    "HoP": [12000, 14000],
    "spells": ["Conceal", "Frost", "Hail", "Cool"],
    "trust": 5,
    "likedCandle": "light_blue"
  }],
  [15, {
    "spirit": "Will O' Wisp",
    "type": "Lesser Fae",
    "court": "Lunar",
    "conjureMsg": "You feel a serene peace. A §5Will O' Wisp§r guides your path, as you guide it in return.",
    "likedOffering": "minecraft:redstone",
    "dislikedOffering": "minecraft:paper",
    "HoP": [15000, 17000],
    "spells": ["Conceal", "Return", "Direct"],
    "trust": 10,
    "likedCandle": "magenta"
  }],
];